PUT http://localhost:3001/api/tuotteet/60cf1e251f1ed4147c916ed6
Content-type: application/json

{
    "nimi": "Kaasunaamari",
    "kategoriat": [
        "Post-apo",
        "Suojavaruste"
    ],
    "lkm": 9,
    "hinta": 6,
    "kuvaus": "Nasseja. Kumia. Ei suojaa kaasulta oikeasti. Eikä muultakaan.",
    "img": "./images/item-9.jpg"
}